
# Utility For Creating Files Of Set Size & Variable Extensions With Random Content.


import os, string, random
from base64 import b64encode
from os import urandom

def create_extension(i):
    extension_list = ['.txt',
         '.exe',
         '.php',
         '.pl',
         '.7z',
         '.rar',
         '.m4a',
         '.wma',
         '.avi',
         '.wmv',
         '.csv',
         '.d3dbsp',
         '.sc2save',
         '.sie',
         '.sum',
         '.ibank',
         '.t13',
         '.t12',
         '.qdf',
         '.gdb',
         '.tax',
         '.pkpass',
         '.bc6',
         '.bc7',
         '.bkp',
         '.qic',
         '.bkf',
         '.sidn',
         '.sidd',
         '.mddata',
         '.itl',
         '.itdb',
         '.icxs',
         '.hvpl',
         '.hplg',
         '.hkdb',
         '.mdbackup',
         '.syncdb',
         '.gho',
         '.cas',
         '.svg',
         '.map',
         '.wmo',
         '.itm',
         '.sb',
         '.fos',
         '.mcgame',
         '.vdf',
         '.ztmp',
         '.sis',
         '.sid',
         '.ncf',
         '.menu',
         '.layout',
         '.dmp',
         '.blob',
         '.esm',
         '.001',
         '.vtf',
         '.dazip',
         '.fpk',
         '.mlx',
         '.kf',
         '.iwd',
         '.vpk',
         '.tor',
         '.psk',
         '.rim',
         '.w3x',
         '.fsh',
         '.ntl',
         '.arch00',
         '.lvl',
         '.snx',
         '.cfr',
         '.ff',
         '.vpp_pc',
         '.lrf',
         '.m2',
         '.mcmeta',
         '.vfs0',
         '.mpqge',
         '.kdb',
         '.db0',
         '.mp3',
         '.upx',
         '.rofl',
         '.hkx',
         '.bar',
         '.upk',
         '.das',
         '.iwi',
         '.litemod',
         '.asset',
         '.forge',
         '.ltx',
         '.bsa',
         '.apk',
         '.re4',
         '.sav',
         '.lbf',
         '.slm',
         '.bik',
         '.epk',
         '.rgss3a',
         '.pak',
         '.big',
         '.unity3d',
         '.wotreplay',
         '.xxx',
         '.desc',
         '.py',
         '.m3u',
         '.flv',
         '.js',
         '.css',
         '.rb',
         '.png',
         '.jpeg',
         '.p7c',
         '.p7b',
         '.p12',
         '.pfx',
         '.pem',
         '.crt',
         '.cer',
         '.der',
         '.x3f',
         '.srw',
         '.pef',
         '.ptx',
         '.r3d',
         '.rw2',
         '.rwl',
         '.raw',
         '.raf',
         '.orf',
         '.nrw',
         '.mrwref',
         '.mef',
         '.erf',
         '.kdc',
         '.dcr',
         '.cr2',
         '.crw',
         '.bay',
         '.sr2',
         '.srf',
         '.arw',
         '.3fr',
         '.dng',
         '.jpeg',
         '.jpg',
         '.cdr',
         '.indd',
         '.ai',
         '.eps',
         '.pdf',
         '.pdd',
         '.psd',
         '.dbfv',
         '.mdf',
         '.wb2',
         '.rtf',
         '.wpd',
         '.dxg',
         '.xf',
         '.dwg',
         '.pst',
         '.accdb',
         '.mdb',
         '.pptm',
         '.pptx',
         '.ppt',
         '.xlk',
         '.xlsb',
         '.xlsm',
         '.xlsx',
         '.xls',
         '.wps',
         '.docm',
         '.docx',
         '.doc',
         '.odb',
         '.odc',
         '.odm',
         '.odp',
         '.ods',
         '.odt',
         '.sql',
         '.zip',
         '.tar',
         '.tar.gz',
         '.tgz',
         '.biz',
         '.ocx',
         '.html',
         '.htm',
         '.3gp',
         '.srt',
         '.cpp',
         '.mid',
         '.mkv',
         '.mov',
         '.asf',
         '.mpeg',
         '.vob',
         '.mpg',
         '.fla',
         '.swf',
         '.wav',
         '.qcow2',
         '.vdi',
         '.vmdk',
         '.vmx',
         '.gpg',
         '.aes',
         '.ARC',
         '.PAQ',
         '.tar.bz2',
         '.tbk',
         '.bak',
         '.djv',
         '.djvu',
         '.bmp',
         '.cgm',
         '.tif',
         '.tiff',
         '.NEF',
         '.cmd',
         '.class',
         '.jar',
         '.java',
         '.asp',
         '.brd',
         '.sch',
         '.dch',
         '.dip',
         '.vbs',
         '.asm',
         '.pas',
         '.ldf',
         '.ibd',
         '.MYI',
         '.MYD',
         '.frm',
         '.dbf',
         '.SQLITEDB',
         '.SQLITE3',
         '.asc',
         '.lay6',
         '.lay',
         '.ms11 (Security copy)',
         '.sldm',
         '.sldx',
         '.ppsm',
         '.ppsx',
         '.ppam',
         '.docb',
         '.mml',
         '.sxm',
         '.otg',
         '.slk',
         '.xlw',
         '.xlt',
         '.xlm',
         '.xlc',
         '.dif',
         '.stc',
         '.sxc',
         '.ots',
         '.ods',
         '.hwp',
         '.dotm',
         '.dotx',
         '.docm',
         '.DOT',
         '.max',
         '.xml',
         '.uot',
         '.stw',
         '.sxw',
         '.ott',
         '.csr',
         '.key',
         'wallet.dat']
    for extension in extension_list:
        return extension_list[i]

def create_filename(x,i):
        filename = "file" + str(x) + create_extension(i)
        return filename

def generate_random_file(n,file_size):

    random_bytes = urandom(file_size)
    token = b64encode(random_bytes).decode('ascii')
    token = token[0: file_size -1]

    x = 1
    i = 0
    while x <= n: # sets the total number of files produced
        with open(create_filename(x,i), 'w') as fout:
            #fout.write(token[0: file_size -1])
            fout.write(token)
            x+=1
            i+=1
            if i >= 286:
                i = 0
        print('random file with size %f generated ok'%file_size)

# Call Generator with file size in bytes
generate_random_file(10000, 10000000)
